### PR TITLE
Fix mario kart multiplayer timings

### PR DESCRIPTION
**Pull request by tony971**
For an explanation of why this cheat is needed, look [here](http://tasvideos.org/GameResources/N64/MarioKart64/Patches.html).

### CODE REVIEW

**Comment by loganmc10** [comment]
Thanks for submitting this!

GlupeN64 doesn't currently support cheats, that's next on my list, I actually don't know almost anything about N64 cheats so I'll have to do some reading

That page says:

> Thus, these codes result in the game playing at an effective runtime pacing of 50% of normal. To overcome this, it is necessary to use an emulator capable of fast forwarding at 200%. The end result is a normal pacing and very smooth 60 fps in all modes. However the music will be double speed and some frame-rate dependent animations (like power slide smoke) occur twice as often as normal.

That doesn't sound great, is this what happens? If so them these cheats definitely can't be the default setting

**Comment by loganmc10** [comment]
Maybe I read that wrong though, perhaps that paragraph was talking about the 60FPS version the cheats only?

**Comment by tony971** [comment]
Yea, that's talking about the 60fps cheat. The cheat I submitted is this one

  These codes set the game time units per input frame to always be 2, regardless of what the original game specified

**Comment by loganmc10** [comment]
Ya I realized I was reading the wrong paragraph.

I'll work on getting cheats working here, this is actually something that needs to be submitted to mupen64plus-core though, the mupen64plus-core folder in this project is just a copy of their repo

**Comment by tony971** [comment]
I tried submitting an issue but cxd4 edited it, closed it, and set the discussion to contributors only. So at least one dev wants nothing to do with patches on by default. My argument is that unless mupen64plus goes timing-accurate, a patch is better than incorrect behavior.

**Comment by loganmc10** [comment]
hm that is unfortunate. The repo that needs to accept it is actually: https://github.com/mupen64plus/mupen64plus-core, I don't think cxd4 is involved with that group, but I will say that I recently submitted a patch (timing hack) to get Pokemon Puzzle League working and there was a bit of grumbling about that as well (even though the game didn't even start before!)

Have you tested this with mupen64plus to confirm that it works, and that it doesn't cause any issues with single player, etc..? If so, I will get cheats working here, and then I will submit this patch to mupen64plus-core if you'd like.

**Comment by tony971** [comment]
I haven't tested with mupen, but I did this same request for project64 a while back and it didn't have any negative consequences.

https://github.com/project64/project64/pull/607

**Comment by loganmc10** [comment]
Ok well I'll get cheats working sometime around Monday, then I'll create a branch with this fix and we can test it a bit and then submit it to mupen64plus-core.

**Comment by loganmc10** [comment]
@tony971 Ok everything is in this branch:

https://github.com/loganmc10/GLupeN64/tree/cheats

Are you able to build that? GLupeN64 puts the mupen64plus.ini in your RetroArch system dir, so you may need to delete that file so that it can replace it with the new version (it only writes one if there is nothing there)

**Comment by tony971** [comment]
I run windows so if I build it, it'll be uncharted territory. My compiler is visual studio.

**Comment by loganmc10** [comment]
Ok I added cheat support to the master branch, you can download a binary here:

http://loganbuildbot.s3-website-us-east-1.amazonaws.com/

It just doesn't have the Mario Kart stuff in the ini file

You can download your version of the ini file here:

https://raw.githubusercontent.com/tony971/GLupeN64/3d583ff531904d2eb9b374d191f6b00967b3ba13/mupen64plus-core/data/mupen64plus.ini

It should replace an already existing mupen64plus.ini that should be in your RetroArch System Dir (in a "GLupeN64" folder), your system dir might be the directory where your ROM is, or it might be in a folder called "system" inside your RetroArch folder.

**Comment by tony971** [comment]
I've seen the folder before but there wasn't a mupen64plus.ini file inside. Only shader info.

**Comment by loganmc10** [comment]
Ok well this build should create one, as well as a GLideN64.custom.ini

**Comment by tony971** [comment]
Works on my end!

**Comment by loganmc10** [comment]
Ok would you like to submit this to mupen64plus-core or would you like me to? It's a different group than mupen64plus-libretro but you're still likely to get a bit of a "we don't like timing hacks" response

**Comment by tony971** [comment]
I'd rather have someone with more pull than an end user do it. They're not even my cheat codes. I just wanted them implemented for beerio kart lol

**Comment by loganmc10** [comment]
I can't think of a nobler cause than beerio kart.

**Comment by loganmc10** [comment]
This was accepted by mupen64plus-core (https://github.com/mupen64plus/mupen64plus-core/pull/203) and merged here with this commit:

2ad0a894ddddeeba21c513e8394543eed54eee12

**Comment by tony971** [comment]
Thanks! And now I have one last request for you. Since this patch is now in Project64, upstream mupen, and this core, could you bring the discussion back up at the regular mupen libretro core? There's an issue still open but any mention of the patch has been censored out. I cannot comment on it any further.

https://github.com/libretro/mupen64plus-libretro/issues/376

**Comment by loganmc10** [comment]
I can't comment on that issue either. I'm not even sure what kind of cheat support mupen64plus-libretro has (I can see that a call to ```cheat_add_hacks();``` is missing from their ```main_run()``` function, so there would probably be some work involved to gets cheats working, and then add this hack).

Essentially, I don't think anyone over there is going to work on it, they would probably accept a pull request if someone did the coding required though.

**Pull request closed without merging**
